<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\optimiser.ico</ApplicationIcon>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\optimiser.ico" />
    <PackageReference Include="System.Management" Version="10.0.12" />
  </ItemGroup>

</Project>
